bower:
  build: ./docker/bower
composer:
  image: composer/composer
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: wordpress-starter-kit-123
gulp:
  build: ./docker/gulp
wordpress:
  image: wordpress:latest
  ports:
    - "80:80"
  links:
    - db:mysql
    - composer
    - bower
    - gulp
  volumes:
    - ./www:/var/www/html
