bower:
  build: ./docker/bower
composer:
  image: composer/composer:latest
db:
  image: mariadb:latest
  environment:
    #MYSQL_DATABASE: wordpress
    MYSQL_ROOT_PASSWORD: wordpress-starter-kit-123
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: m1ttw0ch13
gulp:
  build: ./docker/gulp
wordpress:
  image: wordpress:latest
  links:
    - bower
    - composer
    - db:mysql
    - gulp
  ports:
    - 8080:80
  volumes:
    - ./wordpress/wp-content/:/Users/karl/Sites/wordpress-starter-kit/www/wp-content
