composer:
  build: ./docker/composer
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: wordpress-starter-kit-123
nodejsbowergulp:
  image: nodejs-bower-gulp
wordpress:
  image: wordpress:latest
  ports:
    - "80:80"
  links:
    - db:mysql
    - composer
    - nodejsbowergulp
  volumes:
    - ./www:/var/www/html
