bower:
  build: .
  dockerfile: Dockerfile.bower
  env_file:
    - env-common.env
  links:
    - npm
  volumes_from:
    - data
composer:
  build: .
  dockerfile: Dockerfile.composer
  env_file:
    - env-common.env
  volumes_from:
    - data
data:
  build: .
  env_file:
    - env-common.env
  dockerfile: Dockerfile.data
  volumes:
    - ./tmp:/tmp
    - ./www:/var/www/html
db:
  env_file:
    - env-common.env
  image: mariadb:latest
  ports:
    - "3306:3306"
  volumes_from:
    - data
gulp:
  build: .
  dockerfile: Dockerfile.gulp
  env_file:
    - env-common.env
  links:
    - bower
    - npm
  volumes_from:
    - data
npm:
  build: .
  dockerfile: Dockerfile.npm
  env_file:
    - env-common.env
  volumes_from:
    - data
wordpress:
  env_file:
    - env-common.env
  image: wordpress:latest
  links:
    - bower
    - composer
    - db:mysql
    - gulp
    - npm
    - wordpress-cli
  ports:
    - 8080:80
  volumes_from:
    - data
  volumes:
    - ./uploads:/var/www/html/wp-content/uploads
  working_dir: /var/www/html
wordpress-cli:
  build: .
  dockerfile: Dockerfile.wordpress-cli
  env_file:
    - env-common.env
  volumes_from:
    - data
  working_dir: /var/www/html
